
---
apiVersion: v1
kind: ServiceAccount
metadata:
    creationTimestamp: null
    name: project6-clone-push
secrets:
    - name: project6-image-registry
    - name: project6-git-repo-github-com

...
