apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: application-onboarding
  name: application-onboarding
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - image: quay.io/project6/application-onboarding:latest
          imagePullPolicy: Always
          name: application-onboarding
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
      securityContext: {}
status: {}
