id: application-onboarding
version: '1.0.0-SNAPSHOT'
specVersion: '0.8'
name: 'application-onboarding'
description: 'A workflow for onboarding applications to OCP cluster'
annotations:
  - "workflow-type/assessment"
dataInputSchema:
  schema: schemas/application-onboarding-input-schema.json
  failOnValidationErrors: true
start: StartState
states:
  - name: StartState
    type: switch
    dataConditions:
    - condition: "${ .someText == \"default\" }"
      transition: GetDefaultWorkflowOptions
    defaultCondition:
      transition: GetEmptyWorkflowOptions
  - name: GetDefaultWorkflowOptions
    type: operation
    actions:
      - name: getDefaultWorkflowOptions
        actionDataFilter:
          toStateData: '. +={workflowOptions: {currentVersion: {id: "", name: ""}, "upgradeOptions": ["move2kube", "Move2Kube"], "migrationOptions": ["greeting", "Greeting"], "newOptions": ["MTAanalysis", "MTA analysis"], "continuationOptions": [], "otherOptions": []}}'
    stateDataFilter:
      output: 
    end: true
  - name: GetEmptyWorkflowOptions
    type: operation
    stateDataFilter:
      output: '. +={workflowOptions: {currentVersion: {}, "upgradeOptions": [], "migrationOptions": [], "newOptions": [], "continuationOptions": [], "otherOptions": []}}'
    end: true
