
---
apiVersion: v1
data:
    ssh-privatekey: PFRPRE86IGluc2VydCB0aGUgcHJpdmF0ZSBzc2gga2V5IGZvciB5b3VyIGdpdCByZXBvPg==
kind: Secret
metadata:
    creationTimestamp: null
    name: project2-git-repo-github-com
type: kubernetes.io/ssh-auth

...
